### PR TITLE
fix: refactor getOrDefault call for API < 24

### LINKED ISSUE #157: Crash in WordpieceTextEncoder
I tried to search for min sdk version and in the manifest it looks like api 8, however in the class
`WordpieceTextEncoder` there is a call using 

``` java
return this.vocabulary.getOrDefault(token,this.vocabulary.get(UNKNOWN));
```
 in `encodeSingle` (line 90) from `WordpieceTextEncoder` I had a crash because  of `getOrDefault`, this is supported only from api 24+ 
would be nice to use something like

```kotlin
return this.vocabulary[token] ?:  this.vocabulary.get(UNKNOWN));
```
version `11.4.1`

(tha's kotlin)

### PR DESCRIPTION
**Pull request by space-pope**
A call to a newer (by Android standards) Java method slipped in to the NLU module, making compatibility with Android API < 24 unnecessarily difficult. There's no reason the newer method is needed here, so I'm rolling it back to the old-school way of doing things.

Closes #157 .

### CODE REVIEW

File: src/main/java/io/spokestack/spokestack/nlu/tensorflow/WordpieceTextEncoder.java [hunk 1]
```diff
@@ -89,8 +89,11 @@ private void loadVocab(String fileName) {
     @Override
     public int encodeSingle(String token) {
         ensureReady();
-        return this.vocabulary.getOrDefault(token,
-              this.vocabulary.get(UNKNOWN));
```
Comment (noelweichbrodt) [inline src/main/java/io/spokestack/spokestack/nlu/tensorflow/WordpieceTextEncoder.java:93]: /me bites tongue

**Review by noelweichbrodt — APPROVED** [review]
